[build]
  publish = "."              # Serve files (index.html, css, js) from root
  functions = "netlify/functions"   # Where your serverless functions live

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
